# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X-k6zyYd78ntaltMYRnHdrc97shlBn1Q
"""

import numpy as np
import matplotlib.pyplot as plt

x = np.linspace(0, 10, 100)
y = np.sin(x)

plt.plot(x, y, label='Sinus(x)', color='blue')

plt.title("Sinus Funksiyasining Grafik")
plt.xlabel("X qiymatlari")
plt.ylabel("Y qiymatlari")
plt.legend()
plt.grid(True)

plt.show()

import numpy as np
import matplotlib.pyplot as plt

np.random.seed(0)
x = np.random.uniform(0, 10, 50)
y = np.random.uniform(0, 10, 50)

plt.scatter(x, y, color='blue', label='Nuqtalar')

plt.title("Tasodifiy Nuqtalar Scatter Grafiki")
plt.xlabel("X qiymatlari")
plt.ylabel("Y qiymatlari")
plt.legend()
plt.grid(True)

plt.show()

import pandas as pd
url = "https://raw.githubusercontent.com/Zulayho06/Maxsus-topshiriq/main/WHO%20COVID-19%20cases.csv"
df = pd.read_csv(url)
print(df.head())
country_data = df.groupby('Country')['New_cases'].sum().reset_index()
top_countries = country_data.sort_values(by='New_cases', ascending=False).head(10)
print(top_countries)
top_countries.to_csv('top_countries_covid.csv', index=False)

import cv2
import matplotlib.pyplot as plt
image_path = 'b.jfif'
image = cv2.imread(image_path)
gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
plt.imshow(gray_image, cmap='gray')
plt.axis('off')
plt.show()

import cv2
import matplotlib.pyplot as plt
image_path = 'd.jfif'
image = cv2.imread(image_path)
gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
plt.imshow(gray_image, cmap='gray')
plt.axis('off')
plt.show()

import cv2
import matplotlib.pyplot as plt
image_path = 'a.jfif'
image = cv2.imread(image_path)
gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
plt.imshow(gray_image, cmap='gray')
plt.axis('off')
plt.show()